### ISSUE TITLE
Set Spreadsheet default colors to be light on dark

### ISSUE THREAD

**Issue by tomster** [turn211/ProDark-FreeCAD-theme#1]
Currently, when creating a new Spreadsheet using this theme, the table itself looks good, i.e. dark background, white lines, the headings and gutter are white on dark, as well.
But the default colors for the cells is still black. While it's possible to simply select the entire table and set its foreground color to white, this is a) cumbersome and b) (at least in the 0.19 builds that I have been using so far) this consumes about 100% CPU for up to several minutes(!).
Since the Spreadsheet workbench doesn't have any preferences (and doesn't seem to honour the "Editor" preferences) I so far haven't found a way to style those default colors.
Perhaps it's a misguided approach to try and solve this via a stylesheet - maybe a change to the Spreadsheet code is required in the end but I wanted to start a discussion about the matter here.

**Comment by turn211** [comment]
We are dealing with 2 colors. These are both ProDark colours . The Black Text, i don't know.

1. Default cell background #3c3c3c - Sadly i think is global across many elements but i haven't yet checked
2. Active Cell #adc5ed -  Stylesheet can change I know.

**Comment by turn211** [comment]
Default Spreadsheet cell background inherits Line 741 QTableview background-color: #3c3c3c 
This affects background-color of Combo View and other Tree and list views. Spreadsheet Mod would have to break this out separately.

**Comment by turn211** [comment]
I fixed the default spreadsheet cell color. Changed to white #ffffff for now. Spreadsheet Mod still should have User Preferences. Download and test if fixes are acceptable.

**Comment by tomster** [comment]
thanks, changing the default to white is an acceptable workaround until we can do it proper. Since the proper solution is outside the scope of theming i'm closing the issue here. thanks for the quick response!
