### ISSUE TITLE
Resizing tree view left a permanent black line

### ISSUE THREAD

**Issue by RadhiFadlillah** [turn211/ProDark-FreeCAD-theme#11]
When resizing the tree view, for some reason there is a black line left in the original tree view border. I'm using `ProDark.qss` from latest commit (5daf4d1) in FreeCAD v0.19:

```
OS: Manjaro Linux (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24291 (Git)
Build type: Release
Branch: makepkg
Hash: 7b5e18a0759de778b74d3a5c17eba9cb815035ac
Python version: 3.9.3
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)
```

Here is the screencast where the bug occurs:

https://user-images.githubusercontent.com/6129042/121479458-3eef3780-c9f4-11eb-80ec-c8d637e0f9a1.mp4

**Comment by dirkolbrich** [comment]
Can confirm. This UI artifact occurs on Mac as well - v0.19 and v0.20-26720, on Mac Intel as well as on Mac M1.
See https://forum.freecadweb.org/viewtopic.php?f=3&t=64942

**Comment by turn211** [comment]
Thanks but cannot reproduce. Taking a guess i would say this is a redrawing problem related to opengl. So graphics drivers.
