### ISSUE TITLE
Create a Preference Pack for ProDark

### ISSUE THREAD

**Issue by luzpaz** [turn211/ProDark-FreeCAD-theme#13]
See https://github.com/dulouie/FreeCAD-modern-config/issues/6

ref: https://github.com/FreeCAD/Addons/issues/16

**Comment by luzpaz** [comment]
@turn211 could you allocate any time to get this done before the v0.20 release? (possibly in a week or 2?)

**Comment by turn211** [comment]
Done.

**Comment by turn211** [comment]
https://github.com/turn211/ProDarkThemePreferencePack Don't know if it works. Can't test it by installing manually. https://forum.freecad.org/viewtopic.php?f=34&t=68771&sid=7fdbe3ef5a9fe6f05e8def16651f5328

**Comment by turn211** [comment]
Complete. https://forum.freecad.org/viewtopic.php?f=34&t=68817&sid=a221b07af184aae0fee5142086d4e988
