### ISSUE TITLE
Black on black elements - practically invisible

### ISSUE THREAD

**Issue by bambukouk** [turn211/ProDark-FreeCAD-theme#14]
Is it possible to customise currently `black separators` in panels?

That's how it looks now (it is actually worse in real life on PC screen :-1: ):
![separators](https://user-images.githubusercontent.com/50301871/164645743-861a09df-dddd-4de3-97bc-3d2b7312bc97.png)

and that is how it could look to make life easier (just an example, perhaps yellow is not the best choice :+1: )
![Screenshot from 2022-04-21 15 32 06](https://user-images.githubusercontent.com/50301871/164645864-f49bfb2d-7721-40e7-9b87-30063b13356d.png)

These are not the only things that are `black on black`, 
which would benefit from being able to be customised by user, please.
Is it possible?
How can it be done?

on FreeCAD forum:
https://forum.freecadweb.org/viewtopic.php?f=34&t=55134#p590260

**Comment by turn211** [comment]
Fixed. Check it out. :-)

**Comment by bambukouk** [comment]
Great, thank you 👍
will check it tomorrow (it's late for me tonight)
