### ISSUE TITLE
Background color issues

### ISSUE THREAD

**Issue by luzpaz** [turn211/ProDark-FreeCAD-theme#15]
![image](https://user-images.githubusercontent.com/4140247/168486650-027f95d9-635a-495e-bcb9-3e3bf9cc122a.png)
![image](https://user-images.githubusercontent.com/4140247/168486657-2dbad9f8-525b-41dc-81d1-abbaa42d0f8c.png)

```
OS: Ubuntu 20.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.
Build type: Release
Branch: unknown
Hash: ef37abc4413f343a922964447ff1a4d21ce37ded
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, OCC 7.5.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.56
  * fasteners 0.3.41
  * FeedsAndSpeeds 0.4.0
  * Assembly3 0.11.3
  * Assembly4 0.11.12
```

Ref: https://forum.freecadweb.org/viewtopic.php?f=34&t=68700&p=595389#p595389

**Comment by turn211** [comment]
Fixed
