### ISSUE TITLE
Test Modern icon theme with Prodark

### ISSUE THREAD

**Issue by luzpaz** [turn211/ProDark-FreeCAD-theme#2]
Context: https://forum.freecadweb.org/viewtopic.php?f=34&t=46633&sid=edd7c49d3f5650431d185469b5ee9a65

**Comment by turn211** [comment]
Checked the Modern Icon Theme out. Very Nice! Too much padding and white space around icons for my liking but that is a small detail. Doesn't look like there are any light icons for Dark themes yet.
