### ISSUE TITLE
Nudge tool text tool close to arrow flyout

### ISSUE THREAD

**Issue by turn211** [turn211/ProDark-FreeCAD-theme#5]
Nudge tool text tool close to arrow flyout. Results in not seeing all text.
![Overlapping text in Nudge tool](https://user-images.githubusercontent.com/78619703/107257881-001e8600-69f0-11eb-83a9-8d105de3b76e.png)

**Comment by luzpaz** [comment]
This is related to the external BIM workbench 
/cc @yorikvanhavre

**Comment by yorikvanhavre** [comment]
https://tracker.freecadweb.org/view.php?id=4559

**Comment by turn211** [comment]
Fixed

QToolBar > QPushButton:!checked {
    background-color: #333333; /* Current Working Plane and Nudge */
    border: 1px solid #333333;
    text-align: left;
