### ISSUE TITLE
How can elements of the UI be discovered and changed via the stylesheet?

### ISSUE THREAD

**Issue by luzpaz** [turn211/ProDark-FreeCAD-theme#6]
Is there a chrome dev tools for Qt Designer ?

**Comment by turn211** [comment]
No. Doesn't look like it.

**Comment by turn211** [comment]
I use a Nuts and Bolts method. To modify an element in FreeCAD, I pick the element i think it is in the stylesheet and paint it a bright colour such as pink #CA64EA. Reload the Stylesheet in FreeCAD and look for Pink #CA64EA. When found, I document what element it is that has changed. It is quite fast. I don't really know how a coder would achieve this as I'm a Journeyman Millwright that turned into a General Contractor that has been building Houses for 30 years. ;-) I'm a Designer/Maker type of guy and started using FreeCAD 3 weeks ago. When I started FreeCAD i was impressed but saw little paper cuts scattered about that made FreeCAD look unfinished. (i.e. Black arrows on black background, Black text on black background, etc) My Goal then became I wanted to make it look finished. I poked around the Forum and learned as much as i needed to create a ProDark theme and fix small fonts on 4K monitors. Other than the couple Open Issues here, i have achieved my Goal. :-)

**Comment by turn211** [comment]
I use a Nut and Bolts approach. Open .qss in Visula Code Editor. Choose the Element i want to style. Try to guess what Element it is in the StyleSheet. Add a background: #CA64EA (Bright Pink) property modifier to said Element. Save. Reload Stylesheet in FreeCAD and find the Bright Pink #CA64EA Element. When found i comment in Stylesheet which element it is. Tedious but it works. I'm not a Coder. Lol

**Comment by turn211** [comment]
Where are these comments going? Learning GitHub

**Comment by luzpaz** [comment]
Interesting approach! Fair enough. Thank you so much for you efforts!

**Comment by luzpaz** [comment]
Good news https://github.com/hyarion/FreeCAD_InspectWidgets/issues/1

**Comment by turn211** [comment]
Tried it out. Works great so far. Thanks for the heads up!
