### ISSUE TITLE
Add documentation for color to change in user configuration.

### ISSUE THREAD

**Issue by Sebclem** [turn211/ProDark-FreeCAD-theme#9]
Hi !
First, very nice work !

It will be interesting to have a brief documentation in readme for all the color that we need to change in the Freecad settings ( like 3d view background, colours of start page )
If we can have the hex value for all this settings it will be more easy.

**Comment by turn211** [comment]
Good idea! Soon.

**Comment by turn211** [comment]
Added User #hex colors .txt file and installation how to.
